# Generated by Django 3.1.4 on 2020-12-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KAir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('high', models.IntegerField(blank=True, db_column='High', null=True)),
                ('low', models.IntegerField(blank=True, db_column='Low', null=True)),
                ('open', models.IntegerField(blank=True, db_column='Open', null=True)),
                ('close', models.IntegerField(blank=True, db_column='Close', null=True)),
                ('volume', models.IntegerField(blank=True, db_column='Volume', null=True)),
                ('adj_close', models.IntegerField(blank=True, db_column='Adj Close', null=True)),
            ],
            options={
                'db_table': 'k_air',
                'ordering': ['-date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='date_input',
            fields=[
                ('input_index', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(null=True)),
                ('mon', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
            ],
        ),
    ]
